language: node_js
node_js:
- 0.12.7
addons:
  ssh_known_hosts: eew.p-gn.xyz
  apt:
    packages:
    - sshpass
    - zip
notifications:
  slack:
    secure: dedhMifMMRnN8P77Zbr3ZdhhroiildBPPGSru9par1rbLe4rCF73H+y/YdrSTxezTvdL7vtYaHep3/ybwaTPBDxr9azFqgBS/L6SJtltUQiNQWvBv52Xu00MuZajLehmJUtPD0y8719NIJoYOl4Tt04m0cstT+qTB7zbIUGgEz3016BuFVAv7SDorzlgC2SjuWYxazj8nCpVKxdo5pOZ1o5WxRdAcvdd1Vt3J3/ZOjPr4IvgCIUFH2+ALl0fkPqQ0wNhDLeDtx3qnUZyxoiW4MUBPwyPMIPDL1PI2K4r4RsH/WUCCfv02ZAuu9N+fM34wLCrnUu4mFQWy3OcQgLqw3ryUDfAfeazPt/LjrLc6XuKe2KjNuf8W29pxd1BJPCy65kNKTN8KK2BDMAyU4toCuDUYFIk/2F0Rzl3f4vOh8Voo45rBgp2Tdt672/gG+uSVB6q5f55c03GFmcE/7PxhLjkTcs0OuNjCTctuZNIdJ7FZZCEh2yGelVPYEzKY3qaMrdTxLWn4P3EW/qxQo4iiWvXF24sYLEGkbuw0kGS9vOc/5YX1Y+G+0poZwpgFA/Oq5mYgIOd1KbEuA7c2dHzo5l1+AMKwhiVQFTuyfg+itDYk9uLNeCgDsCPqux38kfMK68zikxkrgqYzR/rtHUhF65KpSLxmt/m9egnP0XM19I=
env:
  global:
    secure: jPCSnvceTU1341cSfiN1chqsSANZ5ZhdZ+mTy2EM/luqylhNCplsyJ39qmorLdQapTrNDjqGcX7w1RtNdsHapgAZprl3iJmcKatLG2ISa16VMath7L7TZ4HClDBEHjHmozd33HjP30DaXIadcxFGVc/oJB9hLkmDFFozlBlbajaiRDG9aJXxXPfNDBCaAz6yDpSapNyss+k/xytAw+pGIYzXta7nvgh+iRiCifwHnTfbjs9rUjrKpQEavn44AmYWKZUvfZ/htvgxJ6m/echHZEnQa35ge0ziMX05XHunzWAJ3dvwj4crnUo3nDYtJCPfMt/H3MfZbXkU5ErtnOlBt6TyZyxcAkwA5TeN907R1DvxE7VbJmg4gVuj01l26vp7R/hyv+4Y0XYBN9+GXkZLxb28R/fqmng2hcJN0NYJqbKnBfDCcAkGAaDRHuqNetpeX7EhaGxIz/b5hmYBS5g+Wec4q8g1r0RsDuGyo4t+NGC3ucJ5npq6jSQM+SozCnMUK8bpumzvwkqn92qzmf3yz6974cEdgXfqcd9ss+gQfU4vxUAeu2XnO2HyQe8gjDX1NryLJCc6JsdQ7vPSJ1XOXwG9VLJzaR/y1uoOQV9hIAtX8g0Gm7r1V6HsStz9MXwWJkooqisIQq9Pb2ePXJ4oBITMoKkgWeLfgb5QuA+ClIg=
install:
- export SSHPASS=$PASSWORD
- npm i
script:
- ./node_modules/.bin/electron-packager ./ Shake --platform=all --arch=all --out=../bin
  --version=0.34.2
- cp ./src/resources/IconMac.icns ../bin/Shake-darwin-x64/Shake.app/Contents/Resources/

- wget http://kurisubrooks.com/static/shake/Info.plist
- cp ./Info.plist ../bin/Shake-darwin-x64/Shake.app/Contents/Info.plist

- cd ../bin/
- tar -czf  shake-osx-x64.tar.gz Shake-darwin-x64/Shake.app
- tar -czf  shake-linux-x64.tar.gz Shake-linux-x64
- tar -czf  shake-linux-x32.tar.gz Shake-linux-ia32
- zip -q -r shake-windows-x64.zip Shake-win32-x64
- zip -q -r shake-windows-x32.zip Shake-win32-ia32

- sshpass -e rsync -zrp ./*.tar.gz travis@eew.kurisubrooks.com:/home/travis/eew/drone/$TRAVIS_BUILD_NUMBER/
- sshpass -e rsync -zrp ./*.zip travis@eew.kurisubrooks.com:/home/travis/eew/drone/$TRAVIS_BUILD_NUMBER/
