language: node_js
node_js:
- '4.1.2'
addons:
  ssh_known_hosts: eew.kurisubrooks.com
  apt:
    packages:
    - sshpass
    - zip
env:
  global:
    secure: jPCSnvceTU1341cSfiN1chqsSANZ5ZhdZ+mTy2EM/luqylhNCplsyJ39qmorLdQapTrNDjqGcX7w1RtNdsHapgAZprl3iJmcKatLG2ISa16VMath7L7TZ4HClDBEHjHmozd33HjP30DaXIadcxFGVc/oJB9hLkmDFFozlBlbajaiRDG9aJXxXPfNDBCaAz6yDpSapNyss+k/xytAw+pGIYzXta7nvgh+iRiCifwHnTfbjs9rUjrKpQEavn44AmYWKZUvfZ/htvgxJ6m/echHZEnQa35ge0ziMX05XHunzWAJ3dvwj4crnUo3nDYtJCPfMt/H3MfZbXkU5ErtnOlBt6TyZyxcAkwA5TeN907R1DvxE7VbJmg4gVuj01l26vp7R/hyv+4Y0XYBN9+GXkZLxb28R/fqmng2hcJN0NYJqbKnBfDCcAkGAaDRHuqNetpeX7EhaGxIz/b5hmYBS5g+Wec4q8g1r0RsDuGyo4t+NGC3ucJ5npq6jSQM+SozCnMUK8bpumzvwkqn92qzmf3yz6974cEdgXfqcd9ss+gQfU4vxUAeu2XnO2HyQe8gjDX1NryLJCc6JsdQ7vPSJ1XOXwG9VLJzaR/y1uoOQV9hIAtX8g0Gm7r1V6HsStz9MXwWJkooqisIQq9Pb2ePXJ4oBITMoKkgWeLfgb5QuA+ClIg=
install:
- export SSHPASS=$PASSWORD
- npm i
script:
- "./node_modules/.bin/electron-packager ./ eew --platform=all --arch=all --out=../bin --version=0.33.0"
- cp ./src/resources/eew.icns ../bin/eew-darwin-x64/eew.app/Contents/Resources/

- wget http://kurisubrooks.com/static/eew/Info.plist

- cp ./Info.plist ../bin/eew-darwin-x64/eew.app/Contents/Info.plist

- cd ../bin/

- tar -czf  eew-osx-x64.tar.gz eew-darwin-x64

- tar -czf  eew-linux-x64.tar.gz eew-linux-x64
- tar -czf  eew-linux-i32.tar.gz eew-linux-ia32

- zip -q -r eew-windows-x64.zip eew-win32-x64
- zip -q -r eew-windows-i32.zip eew-win32-ia32

- sshpass -e rsync -zrp ./*.tar.gz travis@eew.kurisubrooks.com:/home/travis/eew/drone/$TRAVIS_BUILD_NUMBER/
- sshpass -e rsync -zrp ./*.zip travis@eew.kurisubrooks.com:/home/travis/eew/drone/$TRAVIS_BUILD_NUMBER/
