language: node_js
node_js:
- 4.4.3
addons:
  ssh_known_hosts: lumios.kurisubrooks.com
  apt:
    packages:
    - sshpass
    - zip
notifications:
  slack:
    secure: F0BKZor3E0QdeBT63TSVjoEVLE+xcXlPFEbEL3G3yspFotTi4pVsqNyrDD+cidrYuXNfki3LiTurkvcoIgMFHTsZV7RQ8MwfpBDiMSl7G7Uw7OwEI0HyshPHGHt0QMBgLbEfeXfe1lnr4P53uNTsS1x5bmT0CI9vwix/93Qsi7vRcfIqKwVjk689ewwUH4mjxVOypJ+9GqYeMb4eMfHGA++LVIO+9YiAVEv+N6TyieUH2A95phffvbIQbXwQTfq3wsKLcNA0ZXgy62HImcwzGdflK5jd9Xc+q+TSxf0NnauMdFLxytT6zSIkDNRBA7GIAWk7gGxRD5/TqMdcEXjpEGOo/SZFRSIFkKq7GxYXjVbtgSeBJ9zebuIs1Q2C4h+drEtXDE+0/HeyKPnHXBQ0T+5/v+jDJKUm0riO8ClgRdBxz9UrEbIQve6nkbkLUaepN7h5sCjehpu7vtuox3jzLnqnBy+Zdk9pioigs1GLiiSHohrnpDzSK8eYl8nFtZmqiHhwW++HkVpG0LIueRnrazqyv+lZHai0zUPiUuaxuINY+FUq5yNUy79zNORnrJs1pYTFwxOiatYCdBEQLcGrfBwxUIwgkuJ15c/mLq3sTEGAfyC+eh9pDMhMPSIk4NSyBRUIw39KKbFAXPQZM+6ZuVwXa1a36NuyRTPZYNXo+ic=
env:
  global:
    secure: jPCSnvceTU1341cSfiN1chqsSANZ5ZhdZ+mTy2EM/luqylhNCplsyJ39qmorLdQapTrNDjqGcX7w1RtNdsHapgAZprl3iJmcKatLG2ISa16VMath7L7TZ4HClDBEHjHmozd33HjP30DaXIadcxFGVc/oJB9hLkmDFFozlBlbajaiRDG9aJXxXPfNDBCaAz6yDpSapNyss+k/xytAw+pGIYzXta7nvgh+iRiCifwHnTfbjs9rUjrKpQEavn44AmYWKZUvfZ/htvgxJ6m/echHZEnQa35ge0ziMX05XHunzWAJ3dvwj4crnUo3nDYtJCPfMt/H3MfZbXkU5ErtnOlBt6TyZyxcAkwA5TeN907R1DvxE7VbJmg4gVuj01l26vp7R/hyv+4Y0XYBN9+GXkZLxb28R/fqmng2hcJN0NYJqbKnBfDCcAkGAaDRHuqNetpeX7EhaGxIz/b5hmYBS5g+Wec4q8g1r0RsDuGyo4t+NGC3ucJ5npq6jSQM+SozCnMUK8bpumzvwkqn92qzmf3yz6974cEdgXfqcd9ss+gQfU4vxUAeu2XnO2HyQe8gjDX1NryLJCc6JsdQ7vPSJ1XOXwG9VLJzaR/y1uoOQV9hIAtX8g0Gm7r1V6HsStz9MXwWJkooqisIQq9Pb2ePXJ4oBITMoKkgWeLfgb5QuA+ClIg=
install:
- export SSHPASS=$PASSWORD
- npm i
script:
- ./node_modules/.bin/electron-packager ./ Shake --platform=all --arch=all --out=../bin
  --version=0.37.5
- cp ./src/resources/IconMac.icns ../bin/Shake-darwin-x64/Shake.app/Contents/Resources/
- wget https://gist.githubusercontent.com/kurisubrooks/2a9206a148adb7039c4b/raw/4b716f33937827035ed005ba09af54639ed2cda2/Info.plist
- cp ./Info.plist ../bin/Shake-darwin-x64/Shake.app/Contents/Info.plist
- cd ../bin/
- tar -czf  shake-osx-x64.tar.gz Shake-darwin-x64/Shake.app
- tar -czf  shake-linux-x64.tar.gz Shake-linux-x64
- tar -czf  shake-linux-x32.tar.gz Shake-linux-ia32
- zip -q -r shake-windows-x64.zip Shake-win32-x64
- zip -q -r shake-windows-x32.zip Shake-win32-ia32
- sshpass -e rsync -zrp ./*.tar.gz travis@lumios.kurisubrooks.com:/home/travis/eew/drone/$TRAVIS_BUILD_NUMBER/
- sshpass -e rsync -zrp ./*.zip travis@lumios.kurisubrooks.com:/home/travis/eew/drone/$TRAVIS_BUILD_NUMBER/